apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-flux
spec:
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "9.1.11"
  # HelmRelease interval set to 5 minutes (so if the Helm release is manually deleted (using "helm uninstall")
  # it should be recreated not longer than 5 minutes later ... without the need for any git commit in the
  # run-time git repo.
  interval: 5m0s
  install:
    remediation:
      retries: 3
  # Default values can be seen in
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
  - kind: ConfigMap
    name: nginx-values